#!/usr/bin/env bash

ln -s ~/Git/dotfiles/settings.json ~/.config/Code/User
ln -s ~/Git/dotfiles/keybindings.json ~/.config/Code/User

extensions=(
	"13xforever.language-x86-64-assembly"
	"Ionide.Ionide-fsharp"
	"Ionide.Ionide-Paket"
	"James-Yu.latex-workshop"
	"bajdzis.vscode-database"
	"crd551.fasto"
	"formulahendry.code-runner"
	"geddski.macros"
	"jmrog.vscode-nuget-package-manager"
	"ms-python.python"
	"ms-vscode.cpptools"
	"ms-vscode.csharp"
	"schneiderpat.aspnet-helper"
	"streetsidesoftware.code-spell-checker"
	"vscodevim.vim"
	"zhuangtongfa.Material-theme"
)

for i in "${extensions[@]}"
do
	code --install-extension $i
done
